apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-jy8v
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-jy8v@sha256:5ea821cdbd8fb9e3b174b01bc1e9687cb1a52124c7da52e3b337d1f567bec3aa
        name: my-nodejs
        resources: {}
status: {}
