apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-crro
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-crro@sha256:211f891b01197e6ba9ef1ffa76ea260670f61cb729bdf2f48c67026c583442f5
        name: my-python
        resources: {}
status: {}
